// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

type Engine_Expecter struct {
	mock *mock.Mock
}

func (_m *Engine) EXPECT() *Engine_Expecter {
	return &Engine_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: key
func (_m *Engine) Del(key string) error {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Engine_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type Engine_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - key string
func (_e *Engine_Expecter) Del(key interface{}) *Engine_Del_Call {
	return &Engine_Del_Call{Call: _e.mock.On("Del", key)}
}

func (_c *Engine_Del_Call) Run(run func(key string)) *Engine_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Engine_Del_Call) Return(_a0 error) *Engine_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Engine_Del_Call) RunAndReturn(run func(string) error) *Engine_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *Engine) Get(key string) (string, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Engine_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Engine_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *Engine_Expecter) Get(key interface{}) *Engine_Get_Call {
	return &Engine_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *Engine_Get_Call) Run(run func(key string)) *Engine_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Engine_Get_Call) Return(_a0 string, _a1 bool) *Engine_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Engine_Get_Call) RunAndReturn(run func(string) (string, bool)) *Engine_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *Engine) Set(key string, value string) {
	_m.Called(key, value)
}

// Engine_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type Engine_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *Engine_Expecter) Set(key interface{}, value interface{}) *Engine_Set_Call {
	return &Engine_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *Engine_Set_Call) Run(run func(key string, value string)) *Engine_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *Engine_Set_Call) Return() *Engine_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *Engine_Set_Call) RunAndReturn(run func(string, string)) *Engine_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewEngine creates a new instance of Engine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *Engine {
	mock := &Engine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
