// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	wal "github.com/neekrasov/kvdb/internal/database/storage/wal"
)

// WAL is an autogenerated mock type for the WAL type
type WAL struct {
	mock.Mock
}

type WAL_Expecter struct {
	mock *mock.Mock
}

func (_m *WAL) EXPECT() *WAL_Expecter {
	return &WAL_Expecter{mock: &_m.Mock}
}

// Flush provides a mock function with given fields: batch
func (_m *WAL) Flush(batch []wal.WriteEntry) error {
	ret := _m.Called(batch)

	if len(ret) == 0 {
		panic("no return value specified for Flush")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]wal.WriteEntry) error); ok {
		r0 = rf(batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WAL_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type WAL_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
//   - batch []wal.WriteEntry
func (_e *WAL_Expecter) Flush(batch interface{}) *WAL_Flush_Call {
	return &WAL_Flush_Call{Call: _e.mock.On("Flush", batch)}
}

func (_c *WAL_Flush_Call) Run(run func(batch []wal.WriteEntry)) *WAL_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]wal.WriteEntry))
	})
	return _c
}

func (_c *WAL_Flush_Call) Return(_a0 error) *WAL_Flush_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WAL_Flush_Call) RunAndReturn(run func([]wal.WriteEntry) error) *WAL_Flush_Call {
	_c.Call.Return(run)
	return _c
}

// NewWAL creates a new instance of WAL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWAL(t interface {
	mock.TestingT
	Cleanup(func())
}) *WAL {
	mock := &WAL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
