// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NamespacesStorage is an autogenerated mock type for the NamespacesStorage type
type NamespacesStorage struct {
	mock.Mock
}

type NamespacesStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *NamespacesStorage) EXPECT() *NamespacesStorage_Expecter {
	return &NamespacesStorage_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: namespace
func (_m *NamespacesStorage) Append(namespace string) ([]string, error) {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(namespace)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(namespace)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NamespacesStorage_AppendNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type NamespacesStorage_AppendNamespaces_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - namespace string
func (_e *NamespacesStorage_Expecter) Append(namespace interface{}) *NamespacesStorage_AppendNamespaces_Call {
	return &NamespacesStorage_AppendNamespaces_Call{Call: _e.mock.On("Append", namespace)}
}

func (_c *NamespacesStorage_AppendNamespaces_Call) Run(run func(namespace string)) *NamespacesStorage_AppendNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NamespacesStorage_AppendNamespaces_Call) Return(_a0 []string, _a1 error) *NamespacesStorage_AppendNamespaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NamespacesStorage_AppendNamespaces_Call) RunAndReturn(run func(string) ([]string, error)) *NamespacesStorage_AppendNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: namespace
func (_m *NamespacesStorage) Delete(namespace string) error {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NamespacesStorage_DeleteNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type NamespacesStorage_DeleteNamespace_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - namespace string
func (_e *NamespacesStorage_Expecter) Delete(namespace interface{}) *NamespacesStorage_DeleteNamespace_Call {
	return &NamespacesStorage_DeleteNamespace_Call{Call: _e.mock.On("Delete", namespace)}
}

func (_c *NamespacesStorage_DeleteNamespace_Call) Run(run func(namespace string)) *NamespacesStorage_DeleteNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NamespacesStorage_DeleteNamespace_Call) Return(_a0 error) *NamespacesStorage_DeleteNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NamespacesStorage_DeleteNamespace_Call) RunAndReturn(run func(string) error) *NamespacesStorage_DeleteNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: namespace
func (_m *NamespacesStorage) Exists(namespace string) bool {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(namespace)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NamespacesStorage_ExistsNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type NamespacesStorage_ExistsNamespace_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - namespace string
func (_e *NamespacesStorage_Expecter) Exists(namespace interface{}) *NamespacesStorage_ExistsNamespace_Call {
	return &NamespacesStorage_ExistsNamespace_Call{Call: _e.mock.On("Exists", namespace)}
}

func (_c *NamespacesStorage_ExistsNamespace_Call) Run(run func(namespace string)) *NamespacesStorage_ExistsNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NamespacesStorage_ExistsNamespace_Call) Return(_a0 bool) *NamespacesStorage_ExistsNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NamespacesStorage_ExistsNamespace_Call) RunAndReturn(run func(string) bool) *NamespacesStorage_ExistsNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields:
func (_m *NamespacesStorage) List() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NamespacesStorage_ListNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type NamespacesStorage_ListNamespaces_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *NamespacesStorage_Expecter) List() *NamespacesStorage_ListNamespaces_Call {
	return &NamespacesStorage_ListNamespaces_Call{Call: _e.mock.On("List")}
}

func (_c *NamespacesStorage_ListNamespaces_Call) Run(run func()) *NamespacesStorage_ListNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NamespacesStorage_ListNamespaces_Call) Return(_a0 []string, _a1 error) *NamespacesStorage_ListNamespaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *NamespacesStorage_ListNamespaces_Call) RunAndReturn(run func() ([]string, error)) *NamespacesStorage_ListNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: namespace
func (_m *NamespacesStorage) Save(namespace string) error {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(namespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NamespacesStorage_SaveNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type NamespacesStorage_SaveNamespace_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - namespace string
func (_e *NamespacesStorage_Expecter) Save(namespace interface{}) *NamespacesStorage_SaveNamespace_Call {
	return &NamespacesStorage_SaveNamespace_Call{Call: _e.mock.On("Save", namespace)}
}

func (_c *NamespacesStorage_SaveNamespace_Call) Run(run func(namespace string)) *NamespacesStorage_SaveNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *NamespacesStorage_SaveNamespace_Call) Return(_a0 error) *NamespacesStorage_SaveNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *NamespacesStorage_SaveNamespace_Call) RunAndReturn(run func(string) error) *NamespacesStorage_SaveNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// NewNamespacesStorage creates a new instance of NamespacesStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNamespacesStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *NamespacesStorage {
	mock := &NamespacesStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
