// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Sizer is an autogenerated mock type for the Sizer type
type Sizer struct {
	mock.Mock
}

type Sizer_Expecter struct {
	mock *mock.Mock
}

func (_m *Sizer) EXPECT() *Sizer_Expecter {
	return &Sizer_Expecter{mock: &_m.Mock}
}

// Size provides a mock function with given fields:
func (_m *Sizer) Size() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Sizer_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type Sizer_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *Sizer_Expecter) Size() *Sizer_Size_Call {
	return &Sizer_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *Sizer_Size_Call) Run(run func()) *Sizer_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Sizer_Size_Call) Return(_a0 int64) *Sizer_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Sizer_Size_Call) RunAndReturn(run func() int64) *Sizer_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewSizer creates a new instance of Sizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sizer {
	mock := &Sizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
